### ISSUE TITLE
cleanup

### ISSUE THREAD

**Issue by jyeung001** [Madelene/appt-api-app#1]
the following lines, if not needed, should be removed...
https://github.com/Madelene/appt-api-app/blob/master/app/models/appointment.rb#L7-L25

If you decided not to use the _API_ namespace when developing your API, it's better if you remove it as it's not being used...
https://github.com/Madelene/appt-api-app/blob/master/app/controllers/api/appointments_controller.rb

Spacing is off (inconsistent) in the following controller: https://github.com/Madelene/appt-api-app/blob/master/app/controllers/appointments_controller.rb

**Comment by Madelene** [comment]
Hi,

Just fixed the spacing, got rid of the namespace (You're right; I wasn't
using it!), but am now debating on whether or not to keep that code in the
model....

Working on end_time _not_ being before start_time as well. (So there is no
time travel with these APIs?) :)

Thanks for the feedback!
Maddie

On 30 November 2015 at 11:11, Joe Yeung notifications@github.com wrote:

> the following lines, if not needed, should be removed...
> 
> https://github.com/Madelene/appt-api-app/blob/master/app/models/appointment.rb#L7-L25
> 
> If you decided not to use the _API_ namespace when developing your API,
> it's better if you remove it as it's not being used...
> 
> https://github.com/Madelene/appt-api-app/blob/master/app/controllers/api/appointments_controller.rb
> 
> Spacing is off (inconsistent) in the following controller:
> https://github.com/Madelene/appt-api-app/blob/master/app/controllers/appointments_controller.rb
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Madelene/appt-api-app/issues/1.

## 

Madelene Campos, M.M.

maddiecampos.herokuapp.com
www.madelenecampos.com
